# Generated by Django 3.0.5 on 2021-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('upass', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
